#Autogenerated by ReportLab guiedit do not edit
from reportlab.graphics.charts.legends import Legend
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin
from reportlab.graphics.charts.lineplots import SimpleTimeSeriesPlot
from reportlab.lib.colors import Color

class perfChart(_DrawingEditorMixin,Drawing):
	def __init__(self,width=400,height=200,*args,**kw):
		Drawing.__init__(self,width,height,*args,**kw)
		self._add(self,SimpleTimeSeriesPlot(),name='chart',validate=None,desc=None)
		self._add(self,Legend(),name='legend',validate=None,desc=None)
		self.width       = 772
		self.chart.y               = 20
		self.chart.x               = 122
		self.chart.height          = 150
		self.chart.width           = 540
		self.chart.lines[0].strokeColor = Color(.19,.49,1,1)
		self.chart.lines[1].strokeColor = Color(.2,.199,.199,1)
		self.chart.lines.strokeWidth     = 1.5
		self.legend.colorNamePairs = [(Color(.19,.49,1,1), 'Fund'), (Color(.2,.199,.199,1), 'Index')]
		self.legend.x              = 690
		self.legend.y              = 120
		self.chart.xValueAxis.xLabelFormat            = '{dd}/{mm}/{yy}'
		self.chart.yValueAxis.visibleGrid          = 1
		self.chart.yValueAxis.labelTextFormat         = '%.1f%%'
		self.chart.yValueAxis.avoidBoundSpace         = (10, 0)

if __name__=="__main__": #NORUNTESTS
	perfChart().save(formats=['pdf'],outDir='.',fnRoot=None)