#Autogenerated by ReportLab guiedit do not edit
import reportlab
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin
from reportlab.lib.colors import toColor, Color
from reportlab.graphics.charts.textlabels import Label

class vchart(_DrawingEditorMixin,Drawing):
	def __init__(self,width=400,height=200,*args,**kw):
		Drawing.__init__(self,width,height,*args,**kw)
		self.width       = 772
		self.height      = 280
		self._add(self,Label(),name='title',validate=None,desc=None)
		self.title._text            = 'MTD Theme Returns'
		self._add(self,reportlab.graphics.charts.barcharts.VerticalBarChart(),name="chart",validate=None,desc=None)
		self.chart.width            = 700
		self.chart.height           = 220
		self.chart.data             = [(-0.31, -0.26, -0.25, -0.24, -0.23, -0.22, -0.21, -0.2, -0.19, -0.18, -0.17, -0.16, -0.15, -0.14, -0.13, -0.12, -0.11, -0.1, -0.09, -0.08, -0.07, -0.06, -0.05, -0.04, -0.03, -0.02, -0.01, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23)]
		self.chart.barLabelArray    = None
		self.chart.categoryAxis._tickValues          = None
		self.chart.categoryAxis.visibleTicks         = 0
		self.chart.categoryAxis.visibleAxis          = 0
		self._add(self,Label(),name='yAxistitle',validate=None,desc=None)
		self.yAxistitle.angle            = 90
		self.yAxistitle._text            = 'as % of AUM'
		self.yAxistitle.x                = 7
		self.chart.valueAxis.visibleAxis             = 0
		self.chart.valueAxis.labelTextFormat         = lambda v: '%.1f%%' % v
		self.chart.bars[0].fillColor   =  toColor(0x4a6dbd)
		self.chart.bars[0].strokeColor   = Color(.290196,.427451,.741176,1)
		self.chart.categoryAxis.categoryNames        = ['CL%02d' % i for i in xrange(52)]
		self.chart.categoryAxis.labels.angle            = 90
		self.chart.categoryAxis.labels.boxTarget='lo'
		self.chart.x                = 45
		self.chart.categoryAxis.labelAxisMode='axispmv'
		self.chart.categoryAxis.labels.boxAnchor='e'
		self.chart.categoryAxis.labels.textAnchor='end'
		self.chart.categoryAxis.labels.dy  = -2
		self.yAxistitle.y                = 140
		self.title.fontSize         = 12
		self.title.y                = 260
		self.title.x                = 386

if __name__=="__main__": #NORUNTESTS
	vchart().save(formats=['pdf'],outDir='.',fnRoot=None)